baseURL = 'https://webengineering-geli-trsi-github-io.pages.dev/'
languageCode = 'en-us'
title = 'Webengineering-Projekt by GELI and TRSI'
copyright = '© 2025-{year} GELI und TRSI Alle rechte vorbehalten.'
